### ISSUE TITLE
Is or will Elasticsearch 1.5 be supported in the future?

### ISSUE THREAD

**Issue by mehrad-rafigh** [cleverage/play2-elasticsearch#62]
Hey guys,

I want to develop a web app using Elasticsearch and the Play Framework. The question I have is, if the newest version of elasticsearch, which is 1.5 by the time of this post, will be supported. Thanks!

**Comment by mantsak** [comment]
+1 for elasticsearch 1.5.2 and/or Play 2.3.9/2.4.0
